@startuml Drukmeter
skinparam ClassAttributeIconSize 0

class InvoerObserver{

}

class UitvoerObserver{

}

interface IObserver{

}

class DrukPascal {

}

interface ISubject

InvoerObserver <|.up. IObserver
UitvoerObserver <|.up. IObserver
ISubject -right- IObserver

ISubject --|> DrukPascal


@enduml